# Generated by Django 5.2.2 on 2025-08-19 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNguoiNhan', models.CharField(max_length=200)),
                ('SDTNguoiNhan', models.CharField(max_length=10)),
                ('DiaChi', models.CharField(max_length=200)),
                ('ThoiGianDat', models.DateTimeField()),
                ('DaNhan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DanhMucChinh', models.CharField(max_length=200)),
                ('DanhMucPhu', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenNguoiDung', models.CharField(max_length=200)),
                ('MatKhau', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenSanPham', models.CharField(max_length=200)),
                ('HinhAnh', models.ImageField(upload_to='AnhSanPham/')),
                ('Gia', models.PositiveBigIntegerField()),
                ('LoaiSanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothingShop.loaisanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoLuong', models.IntegerField()),
                ('DonHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothingShop.donhang')),
                ('SanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothingShop.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='donhang',
            name='NguoiDat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothingShop.taikhoan'),
        ),
    ]
