# Generated by Django 5.2.2 on 2025-08-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='TenSanPham',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='Email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='MatKhau',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='TenNguoiDung',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
