# Generated by Django 5.2.2 on 2025-08-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingShop', '0002_alter_sanpham_tensanpham_alter_taikhoan_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='TenNguoiDung',
            field=models.CharField(error_messages={'blank': 'Không được để trống', 'unique': 'Trùng tên người dùng'}, max_length=200, unique=True),
        ),
    ]
