# Generated by Django 5.2.2 on 2025-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingShop', '0003_alter_taikhoan_tennguoidung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taikhoan',
            name='Email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='taikhoan',
            name='TenNguoiDung',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
