# Generated by Django 5.2.2 on 2025-08-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingShop', '0004_alter_taikhoan_email_alter_taikhoan_tennguoidung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='ThoiGianDat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
